### ISSUE TITLE
Overflow Error

### ISSUE THREAD

**Issue by LordReya** [antonsau/DEX-prices-monitor#1]
How do you solve this one?

I can't start the monitor because of this:

```/usr/local/bin/python3 "/Users/lordreya/Documents/arbitrage bot/DEX-prices-monitor-master/main.py"
lordreya@Lords-Air DEX-prices-monitor-master % /usr/local/bin/python3 "/Users/lordreya/Documents/arbitrage bot/
DEX-prices-monitor-master/main.py"
Traceback (most recent call last):
  File "/Users/lordreya/Documents/arbitrage bot/DEX-prices-monitor-master/main.py", line 100, in <module>
    df_tokens['max_amount_for_input_token_wei_int'] = (df_tokens['max_amount_for_input_token'] *
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/ops/common.py", line 72, in new_method
    return method(self, other)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/arraylike.py", line 119, in __mul__
lordreya@Lords-Air DEX-prices-monitor-master % /usr/local/bin/python3 "/Users/lordreya/Documents/arbitrage bot/
DEX-prices-monitor-master/main.py"
Traceback (most recent call last):
  File "/Users/lordreya/Documents/arbitrage bot/DEX-prices-monitor-master/main.py", line 100, in <module>
    df_tokens['max_amount_for_input_token_wei_int'] = (df_tokens['max_amount_for_input_token'] * #here is a problem
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/ops/common.py", line 72, in new_method
    return method(self, other)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/arraylike.py", line 119, in __mul__
    return self._arith_method(other, operator.mul)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/series.py", line 6262, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/base.py", line 1325, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 226, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 165, in _na_arithmetic_op
    result = func(left, right)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/computation/expressions.py", line 242, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/computation/expressions.py", line 71, in _evaluate_standard
    return op(a, b)
OverflowError: repeated string is too long```

**Comment by smypmsa** [comment]
Thank you for opening the issue. I'll try to check it next week. Let me know if you solve it earlier than me.

**Comment by LordReya** [comment]
> Thank you for opening the issue. I'll try to check it next week. Let me know if you solve it earlier than me.

Sure thing

**Comment by LordReya** [comment]
@antonsau Any update? I couldn't find the error.

**Comment by smypmsa** [comment]
> 

Hi! Sorry for the delay. It seems that the problem was with the web3 provider. I changed it to the current value from infura and checked - it works fine.

**Comment by LordReya** [comment]
> > 
> 
> Hi! Sorry for the delay. It seems that the problem was with the web3 provider. I changed it to the current value from infura. and checked - it works fine.

All good! Happy that it works now
